### ISSUE TITLE
GaitTypes not working properly

### ISSUE THREAD

**Issue by Velt1** [Bin4ry/free-dog-sdk#11]
I have the Go1 EDU and the GaitType CLIMB_STAIR acts like the running mode. The TROT_OBSTACLE makes my robot walk very weird, like it would fall every moment. And I also wanted to ask what the Speed Levels do?

**Comment by MAVProxyUser** [comment]
@Velt1 what is the expected behavior? Does the normal Unitree SDK do something *different*? Please verbosely explain what happens when you attempt the same thing via the OEM SDK. 

Could be a typo. Edit enums.py and set TROT_OBSTACLE to 4, and try again. Let me know the result of your test. 
![image](https://github.com/Bin4ry/free-dog-sdk/assets/2904396/f747a8cb-323f-4675-a9ea-5b3f8e1c68d7)

**Comment by Velt1** [comment]
Yeah it works like that:
class GaitType(Enum):
    IDLE = 0
    TROT = 1
    TROT_RUNNING = 2
    CLIMB_STAIR = 3
    TROT_OBSTACLE = 4
    
   But do I have to pay attention to some parameters when using the climb stairs mode?
   Because sometimes it just falls down

**Comment by MAVProxyUser** [comment]
How does it behave with Unitree SDK? I suspect the safety limits are getting triggered perhaps?  Someone needs to put some initiative in to implementing them. https://github.com/Bin4ry/free-dog-sdk/issues/7

**Comment by MAVProxyUser** [comment]
First issue was fixed here. https://github.com/Bin4ry/free-dog-sdk/commit/a83f21c46156251eea6dba8ac8ec7dbe8e1d2316 after testing with the normal SDK, let us know how it handles, and open a new issue if you think the Safety Limits are being exceeded, or something else causing the falling. do you have any log file entries when this happens from the dog?
